### ISSUE TITLE
Reactor aleady Installed

### ISSUE THREAD

**Issue by einsli** [clemfromspace/scrapy-puppeteer#2]
I follow the official website documentation, after importing those packages, execute the crawler startup script, and then throw the following error：
```
raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```
 I use ScrapyCommand to start my spider, I hope someone could help me

**Comment by FGallenkamp** [comment]
Read the README:
> The main issue when running Scrapy and Puppeteer together is that Scrapy is using Twisted and that Pyppeteeer (the python port of puppeteer we are using) is using asyncio for async stuff.

>Luckily, we can use the Twisted's asyncio reactor to make the two talking with each other.

>That's why you cannot use the buit-in scrapy command line (installing the default reactor), you will have to use the scrapyp one, provided by this module.

>If you are running your spiders from a script, you will have to make sure you install the asyncio reactor before importing scrapy or doing anything else:

>import asyncio
>from twisted.internet import asyncioreactor

>asyncioreactor.install(asyncio.get_event_loop())

**Comment by thernstig** [comment]
@clemfromspace It seems Scrapy is getting some much needed love and is very active nowadays, see https://github.com/scrapy/scrapy/commits/master

It seems that asyncio support is finally comming! See https://github.com/scrapy/scrapy/pull/4010 - I think that when it does, maybe you should consider seeing if this Spider can be merged into the main code base, if the Scrapy team agress? At least update the README  here once in place :)

**Comment by clemfromspace** [comment]
@thernstig Sorry for the (very) late answer, The `asyncio` support is indeed a really good news!
I don't think the Scrapy team will want to integrate this spider into their codebase, as they already maintain a "Pupeeter-like" javascript renderer: Splash.
I will surely update this package though 👍

**Comment by thernstig** [comment]
Ok sounds good 😃 Too bad splash is not-so-good.
